package com.github.jershell.shadcn.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.toArgb
import com.composeunstyled.theme.ThemeToken
import com.github.jershell.shadcn.theme.ShadcnPreset
import com.github.jershell.shadcn.theme.darkPalette
import com.github.jershell.shadcn.theme.lightPalette

private fun hexOf(color: Color): String =
    (color.toArgb() and 0xFFFFFF).toString(16).uppercase().padStart(6, '0')

private fun colorMapLiteral(colors: Map<ThemeToken<Color>, Color>, indent: String): String {
    if (colors.isEmpty()) return "emptyMap()"
    val entries = colors.entries.joinToString(",\n") { (token, color) ->
        "$indent    \"${token.name}\" to \"${hexOf(color)}\","
    }
    return buildString {
        appendLine("mapOf(")
        append(entries)
        append("\n$indent)")
    }
}

/**
 * Generates the Kotlin snippet that reproduces the resolved theme in another app
 * that depends on the uikit: a `ShadcnPreset` carrying the builder parameters plus
 * the fully resolved light/dark per-token color maps (so the receiving app does not
 * need the same scales/version to render identically).
 *
 * Usage in the target app: `ShadcnTheme(preset = preset) { /* app */ }`.
 */
public fun generatePresetCode(preset: ShadcnPreset?): String {
    val p = preset ?: ShadcnPreset()
    val light = p.lightPalette().orEmpty()
    val dark = p.darkPalette().orEmpty()

    return buildString {
        appendLine("// Generated by the shadcn-multiplatform theme builder.")
        appendLine("// Apply in your app: ShadcnTheme(preset = preset) { /* content */ }")
        appendLine("// Requires: com.github.jershell:shadcn-multiplatform uikit dependency.")
        appendLine("val preset = ShadcnPreset(")
        p.style?.let { appendLine("    style = \"$it\",") }
        appendLine("    baseColor = \"${p.baseColor}\",")
        p.theme?.let { appendLine("    theme = \"$it\",") }
        p.chartColor?.let { appendLine("    chartColor = \"$it\",") }
        p.font?.let { appendLine("    font = \"$it\",") }
        p.iconLibrary?.let { appendLine("    iconLibrary = \"$it\",") }
        p.menuStyle?.let { appendLine("    menuStyle = \"$it\",") }
        p.menuAccent?.let { appendLine("    menuAccent = \"$it\",") }
        p.radius?.let { appendLine("    radius = $it,") }
        appendLine("    // fully resolved light palette (token name -> #RRGGBB)")
        appendLine("    light = ${colorMapLiteral(light, "")},")
        appendLine("    // fully resolved dark palette (token name -> #RRGGBB)")
        appendLine("    dark = ${colorMapLiteral(dark, "")},")
        append(")")
    }
}
