// Generated by scripts/generate_icon_catalog.py. Do not edit manually.
package com.github.jershell.shadcn.ui.icons

import androidx.compose.ui.graphics.vector.ImageVector

data class IconEntry(
    val copyName: String,
    val slugName: String,
    val vector: () -> ImageVector,
)

data class IconSetInfo(
    val id: String,
    val label: String,
    val copyPrefix: String,
    val iconCount: Int,
)

object IconCatalog {
    val sets: List<IconSetInfo> = listOf(
        IconSetInfo(
            id = "lucide",
            label = "Lucide",
            copyPrefix = "Lucide",
            iconCount = LucideIcons.count,
        ),
        IconSetInfo(
            id = "tabler-outline",
            label = "Tabler Outline",
            copyPrefix = "Tabler.Outline",
            iconCount = TablerOutlineIcons.count,
        ),
        IconSetInfo(
            id = "tabler-filled",
            label = "Tabler Filled",
            copyPrefix = "Tabler.Filled",
            iconCount = TablerFilledIcons.count,
        ),
    )

    fun iconsFor(id: String): List<IconEntry> = when (id) {
        "lucide" -> LucideIcons.icons
        "tabler-outline" -> TablerOutlineIcons.icons
        "tabler-filled" -> TablerFilledIcons.icons
        else -> emptyList()
    }

    fun findSet(id: String): IconSetInfo? = sets.firstOrNull { it.id == id }
}
