// Generated by scripts/generate_icon_catalog.py. Do not edit manually.
package com.github.jershell.shadcn.ui.icons

internal object LucideIcons {
    const val count: Int = 1665

    val icons: List<IconEntry> by lazy {
        buildList {
            LucideIconsPart0.appendTo(this)
            LucideIconsPart1.appendTo(this)
        }
    }
}
