// Generated by scripts/generate_icon_catalog.py. Do not edit manually.
package com.github.jershell.shadcn.ui.icons

internal object TablerOutlineIcons {
    const val count: Int = 4985

    val icons: List<IconEntry> by lazy {
        buildList {
            TablerOutlineIconsPart0.appendTo(this)
            TablerOutlineIconsPart1.appendTo(this)
            TablerOutlineIconsPart2.appendTo(this)
            TablerOutlineIconsPart3.appendTo(this)
            TablerOutlineIconsPart4.appendTo(this)
        }
    }
}
