// Generated by importThemeFromFigmaTokens. Do not edit manually.
package com.github.jershell.shadcn.theme

import androidx.compose.runtime.Composable
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.sp

public object TypographyStyles {
  private val fontFamily: FontFamily
    @Composable
    get() = LocalShadcnFonts.current ?: FontFamily.Default

  public val textBaseBlack: TextStyle
    @Composable
    get() = TextStyle(fontSize = 16.0.sp, lineHeight = 24.0.sp, fontWeight = FontWeight.W900, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textBaseBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 16.0.sp, lineHeight = 24.0.sp, fontWeight = FontWeight.W700, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textBaseExtraBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 16.0.sp, lineHeight = 24.0.sp, fontWeight = FontWeight.W800, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textBaseExtraLight: TextStyle
    @Composable
    get() = TextStyle(fontSize = 16.0.sp, lineHeight = 24.0.sp, fontWeight = FontWeight.W200, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textBaseLight: TextStyle
    @Composable
    get() = TextStyle(fontSize = 16.0.sp, lineHeight = 24.0.sp, fontWeight = FontWeight.W300, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textBaseMedium: TextStyle
    @Composable
    get() = TextStyle(fontSize = 16.0.sp, lineHeight = 24.0.sp, fontWeight = FontWeight.W500, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textBaseRegular: TextStyle
    @Composable
    get() = TextStyle(fontSize = 16.0.sp, lineHeight = 24.0.sp, fontWeight = FontWeight.W400, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textBaseSemiBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 16.0.sp, lineHeight = 24.0.sp, fontWeight = FontWeight.W600, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textBaseThin: TextStyle
    @Composable
    get() = TextStyle(fontSize = 16.0.sp, lineHeight = 24.0.sp, fontWeight = FontWeight.W100, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textLgBlack: TextStyle
    @Composable
    get() = TextStyle(fontSize = 18.0.sp, lineHeight = 28.0.sp, fontWeight = FontWeight.W900, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textLgBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 18.0.sp, lineHeight = 28.0.sp, fontWeight = FontWeight.W700, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textLgExtraBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 18.0.sp, lineHeight = 28.0.sp, fontWeight = FontWeight.W800, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textLgExtraLight: TextStyle
    @Composable
    get() = TextStyle(fontSize = 18.0.sp, lineHeight = 28.0.sp, fontWeight = FontWeight.W200, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textLgLight: TextStyle
    @Composable
    get() = TextStyle(fontSize = 18.0.sp, lineHeight = 28.0.sp, fontWeight = FontWeight.W300, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textLgMedium: TextStyle
    @Composable
    get() = TextStyle(fontSize = 18.0.sp, lineHeight = 28.0.sp, fontWeight = FontWeight.W500, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textLgRegular: TextStyle
    @Composable
    get() = TextStyle(fontSize = 18.0.sp, lineHeight = 28.0.sp, fontWeight = FontWeight.W400, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textLgSemiBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 18.0.sp, lineHeight = 28.0.sp, fontWeight = FontWeight.W600, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textLgThin: TextStyle
    @Composable
    get() = TextStyle(fontSize = 18.0.sp, lineHeight = 28.0.sp, fontWeight = FontWeight.W100, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN2xlBlack: TextStyle
    @Composable
    get() = TextStyle(fontSize = 24.0.sp, lineHeight = 32.0.sp, fontWeight = FontWeight.W900, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN2xlBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 24.0.sp, lineHeight = 32.0.sp, fontWeight = FontWeight.W700, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN2xlExtraBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 24.0.sp, lineHeight = 32.0.sp, fontWeight = FontWeight.W800, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN2xlExtraLight: TextStyle
    @Composable
    get() = TextStyle(fontSize = 24.0.sp, lineHeight = 32.0.sp, fontWeight = FontWeight.W200, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN2xlLight: TextStyle
    @Composable
    get() = TextStyle(fontSize = 24.0.sp, lineHeight = 32.0.sp, fontWeight = FontWeight.W300, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN2xlMedium: TextStyle
    @Composable
    get() = TextStyle(fontSize = 24.0.sp, lineHeight = 32.0.sp, fontWeight = FontWeight.W500, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN2xlRegular: TextStyle
    @Composable
    get() = TextStyle(fontSize = 24.0.sp, lineHeight = 32.0.sp, fontWeight = FontWeight.W400, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN2xlSemiBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 24.0.sp, lineHeight = 32.0.sp, fontWeight = FontWeight.W600, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN2xlThin: TextStyle
    @Composable
    get() = TextStyle(fontSize = 24.0.sp, lineHeight = 32.0.sp, fontWeight = FontWeight.W100, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN3xlBlack: TextStyle
    @Composable
    get() = TextStyle(fontSize = 30.0.sp, lineHeight = 36.0.sp, fontWeight = FontWeight.W900, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN3xlBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 30.0.sp, lineHeight = 36.0.sp, fontWeight = FontWeight.W700, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN3xlExtraBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 30.0.sp, lineHeight = 36.0.sp, fontWeight = FontWeight.W800, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN3xlExtraLight: TextStyle
    @Composable
    get() = TextStyle(fontSize = 30.0.sp, lineHeight = 36.0.sp, fontWeight = FontWeight.W200, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN3xlLight: TextStyle
    @Composable
    get() = TextStyle(fontSize = 30.0.sp, lineHeight = 36.0.sp, fontWeight = FontWeight.W300, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN3xlMedium: TextStyle
    @Composable
    get() = TextStyle(fontSize = 30.0.sp, lineHeight = 36.0.sp, fontWeight = FontWeight.W500, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN3xlRegular: TextStyle
    @Composable
    get() = TextStyle(fontSize = 30.0.sp, lineHeight = 36.0.sp, fontWeight = FontWeight.W400, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN3xlSemiBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 30.0.sp, lineHeight = 36.0.sp, fontWeight = FontWeight.W600, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN3xlThin: TextStyle
    @Composable
    get() = TextStyle(fontSize = 30.0.sp, lineHeight = 36.0.sp, fontWeight = FontWeight.W100, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN4xlBlack: TextStyle
    @Composable
    get() = TextStyle(fontSize = 36.0.sp, lineHeight = 40.0.sp, fontWeight = FontWeight.W900, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN4xlBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 36.0.sp, lineHeight = 40.0.sp, fontWeight = FontWeight.W700, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN4xlExtraBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 36.0.sp, lineHeight = 40.0.sp, fontWeight = FontWeight.W800, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN4xlExtraLight: TextStyle
    @Composable
    get() = TextStyle(fontSize = 36.0.sp, lineHeight = 40.0.sp, fontWeight = FontWeight.W200, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN4xlLight: TextStyle
    @Composable
    get() = TextStyle(fontSize = 36.0.sp, lineHeight = 40.0.sp, fontWeight = FontWeight.W300, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN4xlMedium: TextStyle
    @Composable
    get() = TextStyle(fontSize = 36.0.sp, lineHeight = 40.0.sp, fontWeight = FontWeight.W500, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN4xlRegular: TextStyle
    @Composable
    get() = TextStyle(fontSize = 36.0.sp, lineHeight = 40.0.sp, fontWeight = FontWeight.W400, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN4xlSemiBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 36.0.sp, lineHeight = 40.0.sp, fontWeight = FontWeight.W600, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN4xlThin: TextStyle
    @Composable
    get() = TextStyle(fontSize = 36.0.sp, lineHeight = 40.0.sp, fontWeight = FontWeight.W100, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN5xlBlack: TextStyle
    @Composable
    get() = TextStyle(fontSize = 48.0.sp, lineHeight = 48.0.sp, fontWeight = FontWeight.W900, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN5xlBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 48.0.sp, lineHeight = 48.0.sp, fontWeight = FontWeight.W700, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN5xlExtraBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 48.0.sp, lineHeight = 48.0.sp, fontWeight = FontWeight.W800, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN5xlExtraLight: TextStyle
    @Composable
    get() = TextStyle(fontSize = 48.0.sp, lineHeight = 48.0.sp, fontWeight = FontWeight.W200, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN5xlLight: TextStyle
    @Composable
    get() = TextStyle(fontSize = 48.0.sp, lineHeight = 48.0.sp, fontWeight = FontWeight.W300, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN5xlMedium: TextStyle
    @Composable
    get() = TextStyle(fontSize = 48.0.sp, lineHeight = 48.0.sp, fontWeight = FontWeight.W500, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN5xlRegular: TextStyle
    @Composable
    get() = TextStyle(fontSize = 48.0.sp, lineHeight = 48.0.sp, fontWeight = FontWeight.W400, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN5xlSemiBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 48.0.sp, lineHeight = 48.0.sp, fontWeight = FontWeight.W600, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN5xlThin: TextStyle
    @Composable
    get() = TextStyle(fontSize = 48.0.sp, lineHeight = 48.0.sp, fontWeight = FontWeight.W100, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN6xlBlack: TextStyle
    @Composable
    get() = TextStyle(fontSize = 60.0.sp, lineHeight = 60.0.sp, fontWeight = FontWeight.W900, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN6xlBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 60.0.sp, lineHeight = 60.0.sp, fontWeight = FontWeight.W700, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN6xlExtraBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 60.0.sp, lineHeight = 60.0.sp, fontWeight = FontWeight.W800, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN6xlExtraLight: TextStyle
    @Composable
    get() = TextStyle(fontSize = 60.0.sp, lineHeight = 60.0.sp, fontWeight = FontWeight.W200, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN6xlLight: TextStyle
    @Composable
    get() = TextStyle(fontSize = 60.0.sp, lineHeight = 60.0.sp, fontWeight = FontWeight.W300, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN6xlMedium: TextStyle
    @Composable
    get() = TextStyle(fontSize = 60.0.sp, lineHeight = 60.0.sp, fontWeight = FontWeight.W500, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN6xlRegular: TextStyle
    @Composable
    get() = TextStyle(fontSize = 60.0.sp, lineHeight = 60.0.sp, fontWeight = FontWeight.W400, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN6xlSemiBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 60.0.sp, lineHeight = 60.0.sp, fontWeight = FontWeight.W600, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN6xlThin: TextStyle
    @Composable
    get() = TextStyle(fontSize = 60.0.sp, lineHeight = 60.0.sp, fontWeight = FontWeight.W100, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN7xlBlack: TextStyle
    @Composable
    get() = TextStyle(fontSize = 72.0.sp, lineHeight = 72.0.sp, fontWeight = FontWeight.W900, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN7xlBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 72.0.sp, lineHeight = 72.0.sp, fontWeight = FontWeight.W700, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN7xlExtraBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 72.0.sp, lineHeight = 72.0.sp, fontWeight = FontWeight.W800, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN7xlExtraLight: TextStyle
    @Composable
    get() = TextStyle(fontSize = 72.0.sp, lineHeight = 72.0.sp, fontWeight = FontWeight.W200, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN7xlLight: TextStyle
    @Composable
    get() = TextStyle(fontSize = 72.0.sp, lineHeight = 72.0.sp, fontWeight = FontWeight.W300, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN7xlMedium: TextStyle
    @Composable
    get() = TextStyle(fontSize = 72.0.sp, lineHeight = 72.0.sp, fontWeight = FontWeight.W500, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN7xlRegular: TextStyle
    @Composable
    get() = TextStyle(fontSize = 72.0.sp, lineHeight = 72.0.sp, fontWeight = FontWeight.W400, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN7xlSemiBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 72.0.sp, lineHeight = 72.0.sp, fontWeight = FontWeight.W600, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN7xlThin: TextStyle
    @Composable
    get() = TextStyle(fontSize = 72.0.sp, lineHeight = 72.0.sp, fontWeight = FontWeight.W100, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN8xlBlack: TextStyle
    @Composable
    get() = TextStyle(fontSize = 96.0.sp, lineHeight = 96.0.sp, fontWeight = FontWeight.W900, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN8xlBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 96.0.sp, lineHeight = 96.0.sp, fontWeight = FontWeight.W700, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN8xlExtraBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 96.0.sp, lineHeight = 96.0.sp, fontWeight = FontWeight.W800, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN8xlExtraLight: TextStyle
    @Composable
    get() = TextStyle(fontSize = 96.0.sp, lineHeight = 96.0.sp, fontWeight = FontWeight.W200, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN8xlLight: TextStyle
    @Composable
    get() = TextStyle(fontSize = 96.0.sp, lineHeight = 96.0.sp, fontWeight = FontWeight.W300, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN8xlMedium: TextStyle
    @Composable
    get() = TextStyle(fontSize = 96.0.sp, lineHeight = 96.0.sp, fontWeight = FontWeight.W500, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN8xlRegular: TextStyle
    @Composable
    get() = TextStyle(fontSize = 96.0.sp, lineHeight = 96.0.sp, fontWeight = FontWeight.W400, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN8xlSemiBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 96.0.sp, lineHeight = 96.0.sp, fontWeight = FontWeight.W600, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN8xlThin: TextStyle
    @Composable
    get() = TextStyle(fontSize = 96.0.sp, lineHeight = 96.0.sp, fontWeight = FontWeight.W100, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN9xlBlack: TextStyle
    @Composable
    get() = TextStyle(fontSize = 128.0.sp, lineHeight = 128.0.sp, fontWeight = FontWeight.W900, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN9xlBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 128.0.sp, lineHeight = 128.0.sp, fontWeight = FontWeight.W700, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN9xlExtraBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 128.0.sp, lineHeight = 128.0.sp, fontWeight = FontWeight.W800, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN9xlExtraLight: TextStyle
    @Composable
    get() = TextStyle(fontSize = 128.0.sp, lineHeight = 128.0.sp, fontWeight = FontWeight.W200, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN9xlLight: TextStyle
    @Composable
    get() = TextStyle(fontSize = 128.0.sp, lineHeight = 128.0.sp, fontWeight = FontWeight.W300, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN9xlMedium: TextStyle
    @Composable
    get() = TextStyle(fontSize = 128.0.sp, lineHeight = 128.0.sp, fontWeight = FontWeight.W500, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN9xlRegular: TextStyle
    @Composable
    get() = TextStyle(fontSize = 128.0.sp, lineHeight = 128.0.sp, fontWeight = FontWeight.W400, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN9xlSemiBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 128.0.sp, lineHeight = 128.0.sp, fontWeight = FontWeight.W600, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textN9xlThin: TextStyle
    @Composable
    get() = TextStyle(fontSize = 128.0.sp, lineHeight = 128.0.sp, fontWeight = FontWeight.W100, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textSmBlack: TextStyle
    @Composable
    get() = TextStyle(fontSize = 14.0.sp, lineHeight = 20.0.sp, fontWeight = FontWeight.W900, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textSmBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 14.0.sp, lineHeight = 20.0.sp, fontWeight = FontWeight.W700, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textSmExtraBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 14.0.sp, lineHeight = 20.0.sp, fontWeight = FontWeight.W800, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textSmExtraLight: TextStyle
    @Composable
    get() = TextStyle(fontSize = 14.0.sp, lineHeight = 20.0.sp, fontWeight = FontWeight.W200, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textSmLight: TextStyle
    @Composable
    get() = TextStyle(fontSize = 14.0.sp, lineHeight = 20.0.sp, fontWeight = FontWeight.W300, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textSmMedium: TextStyle
    @Composable
    get() = TextStyle(fontSize = 14.0.sp, lineHeight = 20.0.sp, fontWeight = FontWeight.W500, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textSmRegular: TextStyle
    @Composable
    get() = TextStyle(fontSize = 14.0.sp, lineHeight = 20.0.sp, fontWeight = FontWeight.W400, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textSmSemiBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 14.0.sp, lineHeight = 20.0.sp, fontWeight = FontWeight.W600, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textSmThin: TextStyle
    @Composable
    get() = TextStyle(fontSize = 14.0.sp, lineHeight = 20.0.sp, fontWeight = FontWeight.W100, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textXlBlack: TextStyle
    @Composable
    get() = TextStyle(fontSize = 20.0.sp, lineHeight = 28.0.sp, fontWeight = FontWeight.W900, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textXlBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 20.0.sp, lineHeight = 28.0.sp, fontWeight = FontWeight.W700, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textXlExtraBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 20.0.sp, lineHeight = 28.0.sp, fontWeight = FontWeight.W800, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textXlExtraLight: TextStyle
    @Composable
    get() = TextStyle(fontSize = 20.0.sp, lineHeight = 28.0.sp, fontWeight = FontWeight.W200, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textXlLight: TextStyle
    @Composable
    get() = TextStyle(fontSize = 20.0.sp, lineHeight = 28.0.sp, fontWeight = FontWeight.W300, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textXlMedium: TextStyle
    @Composable
    get() = TextStyle(fontSize = 20.0.sp, lineHeight = 28.0.sp, fontWeight = FontWeight.W500, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textXlRegular: TextStyle
    @Composable
    get() = TextStyle(fontSize = 20.0.sp, lineHeight = 28.0.sp, fontWeight = FontWeight.W400, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textXlSemiBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 20.0.sp, lineHeight = 28.0.sp, fontWeight = FontWeight.W600, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textXlThin: TextStyle
    @Composable
    get() = TextStyle(fontSize = 20.0.sp, lineHeight = 28.0.sp, fontWeight = FontWeight.W100, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textXsBlack: TextStyle
    @Composable
    get() = TextStyle(fontSize = 12.0.sp, lineHeight = 16.0.sp, fontWeight = FontWeight.W900, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textXsBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 12.0.sp, lineHeight = 16.0.sp, fontWeight = FontWeight.W700, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textXsExtraBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 12.0.sp, lineHeight = 16.0.sp, fontWeight = FontWeight.W800, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textXsExtraLight: TextStyle
    @Composable
    get() = TextStyle(fontSize = 12.0.sp, lineHeight = 16.0.sp, fontWeight = FontWeight.W200, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textXsLight: TextStyle
    @Composable
    get() = TextStyle(fontSize = 12.0.sp, lineHeight = 16.0.sp, fontWeight = FontWeight.W300, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textXsMedium: TextStyle
    @Composable
    get() = TextStyle(fontSize = 12.0.sp, lineHeight = 16.0.sp, fontWeight = FontWeight.W500, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textXsRegular: TextStyle
    @Composable
    get() = TextStyle(fontSize = 12.0.sp, lineHeight = 16.0.sp, fontWeight = FontWeight.W400, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textXsSemiBold: TextStyle
    @Composable
    get() = TextStyle(fontSize = 12.0.sp, lineHeight = 16.0.sp, fontWeight = FontWeight.W600, letterSpacing = 0.0.sp, fontFamily = fontFamily)

  public val textXsThin: TextStyle
    @Composable
    get() = TextStyle(fontSize = 12.0.sp, lineHeight = 16.0.sp, fontWeight = FontWeight.W100, letterSpacing = 0.0.sp, fontFamily = fontFamily)
}
