// Generated by importThemeFromFigmaTokens. Do not edit manually.
package com.github.jershell.shadcn.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import com.composeunstyled.theme.ThemeProperty
import com.composeunstyled.theme.ThemeToken

public object ColorTokens {
  public val accent: ThemeToken<Color> = ThemeToken("accent")

  public val accentForeground: ThemeToken<Color> = ThemeToken("accentForeground")

  public val background: ThemeToken<Color> = ThemeToken("background")

  public val backgroundColor: ThemeToken<Color> = ThemeToken("backgroundColor")

  public val border: ThemeToken<Color> = ThemeToken("border")

  public val card: ThemeToken<Color> = ThemeToken("card")

  public val cardForeground: ThemeToken<Color> = ThemeToken("cardForeground")

  public val chartToken1: ThemeToken<Color> = ThemeToken("chartToken1")

  public val chartToken2: ThemeToken<Color> = ThemeToken("chartToken2")

  public val chartToken3: ThemeToken<Color> = ThemeToken("chartToken3")

  public val chartToken4: ThemeToken<Color> = ThemeToken("chartToken4")

  public val chartToken5: ThemeToken<Color> = ThemeToken("chartToken5")

  public val destructive: ThemeToken<Color> = ThemeToken("destructive")

  public val foreground: ThemeToken<Color> = ThemeToken("foreground")

  public val input: ThemeToken<Color> = ThemeToken("input")

  public val muted: ThemeToken<Color> = ThemeToken("muted")

  public val mutedForeground: ThemeToken<Color> = ThemeToken("mutedForeground")

  public val popover: ThemeToken<Color> = ThemeToken("popover")

  public val popoverForeground: ThemeToken<Color> = ThemeToken("popoverForeground")

  public val primary: ThemeToken<Color> = ThemeToken("primary")

  public val primaryForeground: ThemeToken<Color> = ThemeToken("primaryForeground")

  public val ring: ThemeToken<Color> = ThemeToken("ring")

  public val secondary: ThemeToken<Color> = ThemeToken("secondary")

  public val secondaryForeground: ThemeToken<Color> = ThemeToken("secondaryForeground")

  public val semanticBackground: ThemeToken<Color> = ThemeToken("semanticBackground")

  public val semanticBorder: ThemeToken<Color> = ThemeToken("semanticBorder")

  public val semanticForeground: ThemeToken<Color> = ThemeToken("semanticForeground")

  public val sidebar: ThemeToken<Color> = ThemeToken("sidebar")

  public val sidebarAccent: ThemeToken<Color> = ThemeToken("sidebarAccent")

  public val sidebarAccentForeground: ThemeToken<Color> = ThemeToken("sidebarAccentForeground")

  public val sidebarBorder: ThemeToken<Color> = ThemeToken("sidebarBorder")

  public val sidebarForeground: ThemeToken<Color> = ThemeToken("sidebarForeground")

  public val sidebarPrimary: ThemeToken<Color> = ThemeToken("sidebarPrimary")

  public val sidebarPrimaryForeground: ThemeToken<Color> = ThemeToken("sidebarPrimaryForeground")

  public val sidebarRing: ThemeToken<Color> = ThemeToken("sidebarRing")
}

public object DimTokens {
  public val borderWidth: ThemeToken<Dp> = ThemeToken("borderWidth")

  public val radiusFull: ThemeToken<Dp> = ThemeToken("radiusFull")

  public val radiusLg: ThemeToken<Dp> = ThemeToken("radiusLg")

  public val radiusMd: ThemeToken<Dp> = ThemeToken("radiusMd")

  public val radiusN2xl: ThemeToken<Dp> = ThemeToken("radiusN2xl")

  public val radiusN3xl: ThemeToken<Dp> = ThemeToken("radiusN3xl")

  public val radiusN4xl: ThemeToken<Dp> = ThemeToken("radiusN4xl")

  public val radiusNone: ThemeToken<Dp> = ThemeToken("radiusNone")

  public val radiusSm: ThemeToken<Dp> = ThemeToken("radiusSm")

  public val radiusXl: ThemeToken<Dp> = ThemeToken("radiusXl")

  public val radiusXs: ThemeToken<Dp> = ThemeToken("radiusXs")

  public val strokeWidth: ThemeToken<Dp> = ThemeToken("strokeWidth")
}

public val ColorProps: ThemeProperty<Color> = ThemeProperty("semanticColors")

public val DimProps: ThemeProperty<Dp> = ThemeProperty("semanticDimensions")
