// Generated by importThemeFromFigmaTokens. Do not edit manually.
package com.github.jershell.shadcn.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.MutableState
import androidx.compose.runtime.ProvidableCompositionLocal
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import com.composeunstyled.theme.buildTheme
import androidx.compose.foundation.text.selection.TextSelectionColors
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import com.github.jershell.shadcn.theme.indication.AppNoIndication

enum class ThemePreset {
    Default,
}

internal val LocalThemeIsDark: ProvidableCompositionLocal<MutableState<Boolean>> =
    compositionLocalOf { mutableStateOf(false) }

internal val LocalThemePreset: ProvidableCompositionLocal<ThemePreset> =
    compositionLocalOf { ThemePreset.Default }

private val ShadcnTheme = buildTheme {
    val isDark by LocalThemeIsDark.current
    val palette = if (isDark) themeDarkSemanticColors else themeLightSemanticColors
    defaultIndication = AppNoIndication
    // icons without an explicit tint rendered black: set contentColor from a token
    defaultContentColor = palette.getValue(ColorTokens.foreground)
    // theme font: implicit Text (without an explicit style) inherits LocalTextStyle
    defaultTextStyle = TextStyle(fontFamily = LocalShadcnFonts.current ?: FontFamily.Default)
    // selection:bg-primary selection:text-primary-foreground
    defaultTextSelectionColors = TextSelectionColors(
        backgroundColor = palette.getValue(ColorTokens.primary),
        handleColor = palette.getValue(ColorTokens.primaryForeground),
    )
    properties[ColorProps] = palette
    properties[DimProps] = if (isDark) themeDarkSemanticDimensions else themeLightSemanticDimensions
}

@Composable
fun ShadcnTheme(
    mode: Mode = if (isSystemInDarkTheme()) Mode.Dark else Mode.Light,
    onModeChanged: @Composable (mode: Mode) -> Unit = {},
    content: @Composable () -> Unit,
) {
    val isDark = mode == Mode.Dark
    val isDarkState = remember { mutableStateOf(isDark) }
    LaunchedEffect(isDark) {
        isDarkState.value = isDark
    }
    CompositionLocalProvider(LocalThemeIsDark provides isDarkState) {
        val currentIsDark by isDarkState
        onModeChanged(if (currentIsDark) Mode.Dark else Mode.Light)
        ShadcnTheme(content)
    }
}
