// Generated by importThemeFromFigmaTokens. Do not edit manually.
package com.github.jershell.shadcn.theme

import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp

public class TokenShadow(
  public val radius: Dp,
  public val color: Color,
  public val offset: Offset,
  public val spread: Dp,
)
