#!/usr/bin/env python3
"""Generate IconCatalog.kt from composables icon source jars."""

from __future__ import annotations

import re
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = ROOT / "demoApp/commonApp/src/commonMain/kotlin/com/github/jershell/ui/icons"
GRADLE_CACHE = Path.home() / ".gradle/caches/modules-2/files-2.1/com.composables"
CHUNK_SIZE = 150
MAX_CHUNKS_PER_FILE = 8
SLUG_PATTERN = re.compile(r'name = "([^"]+)"')

ICON_SETS = [
    {
        "id": "lucide",
        "label": "Lucide",
        "copy_prefix": "Lucide",
        "object_name": "LucideIcons",
        "file_name": "LucideIcons.generated.kt",
        "jar_glob": "icons-lucide-cmp-*/**/*sources.jar",
        "file_filter": lambda name: name.endswith(".kt") and not name.endswith("/Lucide.kt"),
        "property_pattern": re.compile(r"val Lucide\.(\w+): ImageVector"),
    },
    {
        "id": "tabler-outline",
        "label": "Tabler Outline",
        "copy_prefix": "Tabler.Outline",
        "object_name": "TablerOutlineIcons",
        "file_name": "TablerOutlineIcons.generated.kt",
        "jar_glob": "icons-tabler-outline-cmp-*/**/*sources.jar",
        "file_filter": lambda name: name.endswith(".kt"),
        "property_pattern": re.compile(r"val Tabler\.Outline\.(\w+): ImageVector"),
    },
    {
        "id": "tabler-filled",
        "label": "Tabler Filled",
        "copy_prefix": "Tabler.Filled",
        "object_name": "TablerFilledIcons",
        "file_name": "TablerFilledIcons.generated.kt",
        "jar_glob": "icons-tabler-filled-cmp-*/**/*sources.jar",
        "file_filter": lambda name: name.endswith(".kt"),
        "property_pattern": re.compile(r"val Tabler\.Filled\.(\w+): ImageVector"),
    },
]

COMMON_IMPORTS = [
    "import androidx.compose.ui.graphics.vector.ImageVector",
    "import com.composables.icons.lucide.Lucide",
    "import com.composables.icons.lucide.*",
    "import com.composables.icons.tabler.Tabler",
    "import com.composables.icons.tabler.filled.*",
    "import com.composables.icons.tabler.outline.*",
]


def find_source_jar(glob_pattern: str) -> Path:
    matches = sorted(GRADLE_CACHE.glob(glob_pattern))
    if not matches:
        raise FileNotFoundError(
            f"Could not find source jar for pattern {glob_pattern}. "
            "Run a Gradle sync/build first."
        )
    return matches[-1]


def parse_icons(jar_path: Path, file_filter, property_pattern: re.Pattern[str]) -> list[tuple[str, str, str]]:
    icons: list[tuple[str, str, str]] = []

    with zipfile.ZipFile(jar_path) as archive:
        for entry in archive.namelist():
            if not file_filter(entry):
                continue

            content = archive.read(entry).decode("utf-8")
            property_match = property_pattern.search(content)
            if not property_match:
                continue

            property_name = property_match.group(1)
            slug_match = SLUG_PATTERN.search(content)
            slug_name = slug_match.group(1) if slug_match else property_name
            icons.append((property_name, slug_name, property_name))

    icons.sort(key=lambda item: item[0].lower())
    return icons


def chunk_icons(icons: list[tuple[str, str, str]]) -> list[list[tuple[str, str, str]]]:
    return [icons[index : index + CHUNK_SIZE] for index in range(0, len(icons), CHUNK_SIZE)]


def split_chunks(chunks: list[list[tuple[str, str, str]]]) -> list[list[list[tuple[str, str, str]]]]:
    return [
        chunks[index : index + MAX_CHUNKS_PER_FILE]
        for index in range(0, len(chunks), MAX_CHUNKS_PER_FILE)
    ]


def render_icon_entry(copy_name: str, slug_name: str, reference: str) -> str:
    return (
        f'IconEntry(copyName = "{copy_name}", slugName = "{slug_name}", '
        f"vector = {{ {reference} }}),"
    )


def render_chunk_function(
    chunk_index: int,
    chunk: list[tuple[str, str, str]],
    copy_prefix: str,
) -> list[str]:
    lines = [f"    private fun chunk{chunk_index}(): List<IconEntry> = listOf("]
    for copy_name, slug_name, property_name in chunk:
        reference = f"{copy_prefix}.{property_name}"
        lines.append(f"        {render_icon_entry(copy_name, slug_name, reference)}")
    lines.append("    )")
    return lines


def render_part_file(
    part_object_name: str,
    chunks: list[list[tuple[str, str, str]]],
    global_chunk_offset: int,
    copy_prefix: str,
) -> str:
    lines = [
        "// Generated by scripts/generate_icon_catalog.py. Do not edit manually.",
        "package com.github.jershell.ui.icons",
        "",
        *COMMON_IMPORTS,
        "",
        f"internal object {part_object_name} {{",
    ]

    for local_index, chunk in enumerate(chunks):
        global_index = global_chunk_offset + local_index
        lines.extend(render_chunk_function(global_index, chunk, copy_prefix))
        lines.append("")

    lines.append("    internal fun appendTo(target: MutableList<IconEntry>) {")
    for local_index, _chunk in enumerate(chunks):
        global_index = global_chunk_offset + local_index
        lines.append(f"        target.addAll(chunk{global_index}())")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def render_set_files(spec: dict, icons: list[tuple[str, str, str]]) -> list[tuple[str, str]]:
    chunks = chunk_icons(icons)
    chunk_groups = split_chunks(chunks)
    generated: list[tuple[str, str]] = []

    if len(chunk_groups) == 1:
        part_object_name = spec["object_name"]
        lines = [
            "// Generated by scripts/generate_icon_catalog.py. Do not edit manually.",
            "package com.github.jershell.ui.icons",
            "",
            *COMMON_IMPORTS,
            "",
            f"internal object {part_object_name} {{",
            f"    const val count: Int = {len(icons)}",
            "",
        ]
        for local_index, chunk in enumerate(chunk_groups[0]):
            lines.extend(render_chunk_function(local_index, chunk, spec["copy_prefix"]))
            lines.append("")
        lines.extend(
            [
                "    val icons: List<IconEntry> by lazy {",
                "        buildList {",
            ]
        )
        for local_index, _chunk in enumerate(chunk_groups[0]):
            lines.append(f"            addAll(chunk{local_index}())")
        lines.extend(["        }", "    }", "}", ""])
        generated.append((spec["file_name"], "\n".join(lines)))
        part_names = [part_object_name]
    else:
        part_names = []
        for part_index, chunk_group in enumerate(chunk_groups):
            part_object_name = f"{spec['object_name']}Part{part_index}"
            part_names.append(part_object_name)
            part_file_name = spec["file_name"].replace(".generated.kt", f"Part{part_index}.generated.kt")
            global_offset = part_index * MAX_CHUNKS_PER_FILE
            content = render_part_file(part_object_name, chunk_group, global_offset, spec["copy_prefix"])
            generated.append((part_file_name, content))

        aggregator_lines = [
            "// Generated by scripts/generate_icon_catalog.py. Do not edit manually.",
            "package com.github.jershell.ui.icons",
            "",
            f"internal object {spec['object_name']} {{",
            f"    const val count: Int = {len(icons)}",
            "",
            "    val icons: List<IconEntry> by lazy {",
            "        buildList {",
        ]
        for part_name in part_names:
            aggregator_lines.append(f"            {part_name}.appendTo(this)")
        aggregator_lines.extend(
            [
                "        }",
                "    }",
                "}",
                "",
            ]
        )
        generated.append((spec["file_name"], "\n".join(aggregator_lines)))

    return generated


def render_catalog_file(sets: list[dict]) -> str:
    lines = [
        "// Generated by scripts/generate_icon_catalog.py. Do not edit manually.",
        "package com.github.jershell.ui.icons",
        "",
        "import androidx.compose.ui.graphics.vector.ImageVector",
        "",
        "data class IconEntry(",
        "    val copyName: String,",
        "    val slugName: String,",
        "    val vector: () -> ImageVector,",
        ")",
        "",
        "data class IconSetInfo(",
        "    val id: String,",
        "    val label: String,",
        "    val copyPrefix: String,",
        "    val iconCount: Int,",
        ")",
        "",
        "object IconCatalog {",
        "    val sets: List<IconSetInfo> = listOf(",
    ]

    for spec in sets:
        lines.extend(
            [
                "        IconSetInfo(",
                f'            id = "{spec["id"]}",',
                f'            label = "{spec["label"]}",',
                f'            copyPrefix = "{spec["copy_prefix"]}",',
                f"            iconCount = {spec['object_name']}.count,",
                "        ),",
            ]
        )

    lines.extend(
        [
            "    )",
            "",
            "    fun iconsFor(id: String): List<IconEntry> = when (id) {",
        ]
    )

    for spec in sets:
        lines.append(f'        "{spec["id"]}" -> {spec["object_name"]}.icons')

    lines.extend(
        [
            "        else -> emptyList()",
            "    }",
            "",
            "    fun findSet(id: String): IconSetInfo? = sets.firstOrNull { it.id == id }",
            "}",
            "",
        ]
    )

    return "\n".join(lines)


def main() -> int:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    parsed_sets: list[dict] = []
    generated_files: set[str] = {"IconCatalog.kt"}

    for spec in ICON_SETS:
        jar_path = find_source_jar(spec["jar_glob"])
        icons = parse_icons(jar_path, spec["file_filter"], spec["property_pattern"])
        if not icons:
            raise RuntimeError(f"No icons parsed from {jar_path}")

        for file_name, content in render_set_files(spec, icons):
            output_path = OUTPUT_DIR / file_name
            output_path.write_text(content, encoding="utf-8")
            generated_files.add(file_name)

        parsed_sets.append(spec)
        chunk_count = len(chunk_icons(icons))
        part_count = len(split_chunks(chunk_icons(icons)))
        print(f'{spec["label"]}: {len(icons)} icons, {chunk_count} chunks, {part_count} file(s)')

    catalog_path = OUTPUT_DIR / "IconCatalog.kt"
    catalog_path.write_text(render_catalog_file(parsed_sets), encoding="utf-8")

    for stale in OUTPUT_DIR.glob("*.generated.kt"):
        if stale.name not in generated_files:
            stale.unlink()

    if (OUTPUT_DIR / "IconCatalog.kt").name not in generated_files:
        pass

    print(f"Wrote catalog to {OUTPUT_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
