package com.github.jershell.theme

import com.github.jershell.theme.models.CollectedToken
import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonObject
import java.io.File

class ThemeCodeGenerator(
    private val packageName: String,
    private val case: ParseColorDesignTokens.TokenCase,
) {
    private val colorClass = ClassName("androidx.compose.ui.graphics", "Color")
    private val dpClass = ClassName("androidx.compose.ui.unit", "Dp")
    private val themePropertyClass = ClassName("com.composeunstyled.theme", "ThemeProperty")
    private val themeTokenClass = ClassName("com.composeunstyled.theme", "ThemeToken")
    private val themeBuilderClass = ClassName("com.composeunstyled.theme", "ThemeBuilder")
    private val buildThemeClass = ClassName("com.composeunstyled.theme", "ThemeKt")
    private val textStyleClass = ClassName("androidx.compose.ui.text", "TextStyle")
    private val fontWeightClass = ClassName("androidx.compose.ui.text.font", "FontWeight")
    private val fontFamilyClass = ClassName("androidx.compose.ui.text.font", "FontFamily")

    fun generate(
        outputDirectory: File,
        primitiveTokens: List<CollectedToken>,
        lightSemantic: List<CollectedToken>,
        darkSemantic: List<CollectedToken>,
        typographyTokens: List<CollectedToken>,
    ) {
        outputDirectory.mkdirs()

        val pathIndex = ValueCodegen.buildPathIndex(primitiveTokens)
        val codegen = ValueCodegen(pathIndex, case)

        writeFile(outputDirectory, generateTokenShadowFile())
        writeFile(outputDirectory, generatePrimitivesFile(primitiveTokens, codegen))
        writeFile(outputDirectory, generateTypographyFile(typographyTokens, codegen))
        writeFile(outputDirectory, generateSemanticTokensFile(lightSemantic, darkSemantic))
        writeFile(outputDirectory, generateThemePalettesFile(lightSemantic, darkSemantic, codegen))
        writeAppThemeFile(outputDirectory)
    }

    private fun writeFile(directory: File, fileSpec: FileSpec) {
        fileSpec.writeTo(directory)
    }

    private fun generateTokenShadowFile(): FileSpec {
        val offsetClass = ClassName("androidx.compose.ui.geometry", "Offset")
        return FileSpec.builder(packageName, "TokenShadow")
            .addFileComment("Generated by importThemeFromFigmaTokens. Do not edit manually.")
            .addType(
                TypeSpec.classBuilder("TokenShadow")
//                    .addModifiers(KModifier.INTERNAL)
                    .primaryConstructor(
                        FunSpec.constructorBuilder()
                            .addParameter("radius", dpClass)
                            .addParameter("color", colorClass)
                            .addParameter("offset", offsetClass)
                            .addParameter("spread", dpClass)
                            .build(),
                    )
                    .addProperty(
                        PropertySpec.builder("radius", dpClass)
                            .initializer("radius")
                            .build(),
                    )
                    .addProperty(
                        PropertySpec.builder("color", colorClass)
                            .initializer("color")
                            .build(),
                    )
                    .addProperty(
                        PropertySpec.builder("offset", offsetClass)
                            .initializer("offset")
                            .build(),
                    )
                    .addProperty(
                        PropertySpec.builder("spread", dpClass)
                            .initializer("spread")
                            .build(),
                    )
                    .build(),
            )
            .build()
    }

    private fun generatePrimitivesFile(
        tokens: List<CollectedToken>,
        codegen: ValueCodegen,
    ): FileSpec {
        val fileBuilder = FileSpec.builder(packageName, "GeneratedPrimitives")
            .addFileComment("Generated by importThemeFromFigmaTokens. Do not edit manually.")
            .addImport("androidx.compose.ui.graphics", "Color")
            .addImport("androidx.compose.ui.text", "TextStyle")
            .addImport("androidx.compose.ui.text.font", "FontFamily")
            .addImport("androidx.compose.ui.text.font", "FontWeight")
            .addImport("androidx.compose.ui.unit", "dp")
            .addImport("androidx.compose.ui.unit", "sp")
            .addImport("androidx.compose.ui.geometry", "Offset")

        val grouped = tokens.groupBy { it.objectName }.toSortedMap()

        grouped.forEach { (objectName, objectTokens) ->
            val objectBuilder = TypeSpec.objectBuilder(objectName)
//                .addModifiers(KModifier.INTERNAL)

            objectTokens.sortedBy { it.propertyName }.forEach { token ->
                val kotlinType = tokenTypeToClassName(token)
                val initializer = primitiveInitializer(token, codegen)
                objectBuilder.addProperty(
                    PropertySpec.builder(token.propertyName, kotlinType)
                        .initializer(initializer)
                        .build()
                )
            }
            fileBuilder.addType(objectBuilder.build())
        }

        return fileBuilder.build()
    }

    private fun generateTypographyFile(
        tokens: List<CollectedToken>,
        codegen: ValueCodegen,
    ): FileSpec {
        val composableClass = ClassName("androidx.compose.runtime", "Composable")
        val fileBuilder = FileSpec.builder(packageName, "GeneratedTypography")
            .addFileComment("Generated by importThemeFromFigmaTokens. Do not edit manually.")
            .addImport("androidx.compose.runtime", "Composable")
            .addImport("androidx.compose.ui.text", "TextStyle")
            .addImport("androidx.compose.ui.text.font", "FontFamily")
            .addImport("androidx.compose.ui.text.font", "FontWeight")
            .addImport("androidx.compose.ui.unit", "sp")

        val objectBuilder = TypeSpec.objectBuilder("TypographyStyles")
//            .addModifiers(KModifier.INTERNAL)

        // The preset font family of the theme builder; resolved live at composition
        // time so the whole typography follows the app font (LocalShadcnFonts).
        objectBuilder.addProperty(
            PropertySpec.builder("fontFamily", fontFamilyClass, KModifier.PRIVATE)
                .getter(
                    FunSpec.getterBuilder()
                        .addAnnotation(AnnotationSpec.builder(composableClass).build())
                        .addStatement("return LocalShadcnFonts.current ?: %T.Default", fontFamilyClass)
                        .build(),
                )
                .build(),
        )

        tokens.sortedBy { it.propertyName }.forEach { token ->
            val json = token.rawValue.jsonObject
            objectBuilder.addProperty(
                PropertySpec.builder(token.propertyName, textStyleClass)
                    .getter(
                        FunSpec.getterBuilder()
                            .addAnnotation(AnnotationSpec.builder(composableClass).build())
                            .addStatement("return %L", codegen.textStyleFromJson(json, fontFamilyExpr = "fontFamily"))
                            .build(),
                    )
                    .build()
            )
        }

        fileBuilder.addType(objectBuilder.build())
        return fileBuilder.build()
    }

    private fun generateSemanticTokensFile(
        lightSemantic: List<CollectedToken>,
        darkSemantic: List<CollectedToken>,
    ): FileSpec {
        val colorTokens = (lightSemantic + darkSemantic)
            .filter { it.type == "color" }
            .distinctBy { it.propertyName }
            .sortedBy { it.propertyName }

        val dimensionTokens = (lightSemantic + darkSemantic)
            .filter { it.type == "dimension" }
            .distinctBy { it.propertyName }
            .sortedBy { it.propertyName }

        val fileBuilder = FileSpec.builder(packageName, "GeneratedSemanticTokens")
            .addFileComment("Generated by importThemeFromFigmaTokens. Do not edit manually.")

        val colorTokensObject = TypeSpec.objectBuilder("ColorTokens")
//            .addModifiers(KModifier.INTERNAL)
        colorTokens.forEach { token ->
            colorTokensObject.addProperty(
                PropertySpec.builder(
                    token.propertyName,
                    themeTokenClass.parameterizedBy(colorClass),
                )
                    .initializer("ThemeToken(%S)", token.propertyName)
                    .build()
            )
        }
        fileBuilder.addType(colorTokensObject.build())

        val dimensionTokensObject = TypeSpec.objectBuilder("DimTokens")
//            .addModifiers(KModifier.INTERNAL)
        dimensionTokens.forEach { token ->
            dimensionTokensObject.addProperty(
                PropertySpec.builder(
                    token.propertyName,
                    themeTokenClass.parameterizedBy(dpClass),
                )
                    .initializer("ThemeToken(%S)", token.propertyName)
                    .build()
            )
        }
        fileBuilder.addType(dimensionTokensObject.build())

        fileBuilder.addProperty(
            PropertySpec.builder(
                "ColorProps",
                themePropertyClass.parameterizedBy(colorClass),
            )
//                .addModifiers(KModifier.INTERNAL)
                .initializer("ThemeProperty(%S)", "semanticColors")
                .build()
        )

        fileBuilder.addProperty(
            PropertySpec.builder(
                "DimProps",
                themePropertyClass.parameterizedBy(dpClass),
            )
//                .addModifiers(KModifier.INTERNAL)
                .initializer("ThemeProperty(%S)", "semanticDimensions")
                .build()
        )

        return fileBuilder.build()
    }

    private fun generateThemePalettesFile(
        lightSemantic: List<CollectedToken>,
        darkSemantic: List<CollectedToken>,
        codegen: ValueCodegen,
    ): FileSpec {
        val fileBuilder = FileSpec.builder(packageName, "GeneratedThemePalettes")
            .addFileComment("Generated by importThemeFromFigmaTokens. Do not edit manually.")

        val lightColors = lightSemantic.filter { it.type == "color" }
        val darkColors = darkSemantic.filter { it.type == "color" }
        val lightDimensions = lightSemantic.filter { it.type == "dimension" }
        val darkDimensions = darkSemantic.filter { it.type == "dimension" }

        fileBuilder.addProperty(
            buildSemanticMapProperty(
                name = "themeLightSemanticColors",
                tokens = lightColors,
                tokenObjectName = "ColorTokens",
                valueType = colorClass,
                codegen = codegen,
            )
        )

        fileBuilder.addProperty(
            buildSemanticMapProperty(
                name = "themeDarkSemanticColors",
                tokens = darkColors,
                tokenObjectName = "ColorTokens",
                valueType = colorClass,
                codegen = codegen,
            )
        )

        fileBuilder.addProperty(
            buildSemanticMapProperty(
                name = "themeLightSemanticDimensions",
                tokens = lightDimensions,
                tokenObjectName = "DimTokens",
                valueType = dpClass,
                codegen = codegen,
            )
        )

        fileBuilder.addProperty(
            buildSemanticMapProperty(
                name = "themeDarkSemanticDimensions",
                tokens = darkDimensions,
                tokenObjectName = "DimTokens",
                valueType = dpClass,
                codegen = codegen,
            )
        )

        return fileBuilder.build()
    }

    private fun buildSemanticMapProperty(
        name: String,
        tokens: List<CollectedToken>,
        tokenObjectName: String,
        valueType: TypeName,
        codegen: ValueCodegen,
    ): PropertySpec {
        val mapType = MAP.parameterizedBy(
            themeTokenClass.parameterizedBy(valueType),
            valueType,
        )

        val initializer = buildString {
            append("mapOf(\n")
            tokens.sortedBy { it.propertyName }.forEach { token ->
                append("    $tokenObjectName.${token.propertyName} to ")
                append(codegen.resolveValue(token.valueString, token.isReference))
                append(",\n")
            }
            append(")")
        }

        return PropertySpec.builder(name, mapType)
            .addModifiers(KModifier.INTERNAL)
            .initializer(initializer)
            .build()
    }

    private fun writeAppThemeFile(outputDirectory: File) {
        val packagePath = packageName.replace('.', '/')
        val themeFile = File(outputDirectory, "$packagePath/Theme.kt")
        themeFile.parentFile.mkdirs()
        themeFile.writeText(
            """
            // Generated by importThemeFromFigmaTokens. Do not edit manually.
            package $packageName

            import androidx.compose.foundation.isSystemInDarkTheme
            import androidx.compose.runtime.Composable
            import androidx.compose.runtime.CompositionLocalProvider
            import androidx.compose.runtime.LaunchedEffect
            import androidx.compose.runtime.MutableState
            import androidx.compose.runtime.ProvidableCompositionLocal
            import androidx.compose.runtime.compositionLocalOf
            import androidx.compose.runtime.getValue
            import androidx.compose.runtime.mutableStateOf
            import androidx.compose.runtime.remember
            import androidx.compose.runtime.setValue
            import com.composeunstyled.theme.buildTheme
            import androidx.compose.foundation.text.selection.TextSelectionColors
            import androidx.compose.ui.text.TextStyle
            import androidx.compose.ui.text.font.FontFamily
            import com.github.jershell.shadcn.theme.indication.AppNoIndication

            enum class ThemePreset {
                Default,
            }

            internal val LocalThemeIsDark: ProvidableCompositionLocal<MutableState<Boolean>> =
                compositionLocalOf { mutableStateOf(false) }

            internal val LocalThemePreset: ProvidableCompositionLocal<ThemePreset> =
                compositionLocalOf { ThemePreset.Default }

            private val ShadcnTheme = buildTheme {
                val isDark by LocalThemeIsDark.current
                val palette = if (isDark) themeDarkSemanticColors else themeLightSemanticColors
                defaultIndication = AppNoIndication
                // icons without an explicit tint rendered black: set contentColor from a token
                defaultContentColor = palette.getValue(ColorTokens.foreground)
                // theme font: implicit Text (without an explicit style) inherits LocalTextStyle
                defaultTextStyle = TextStyle(fontFamily = LocalShadcnFonts.current ?: FontFamily.Default)
                // selection:bg-primary selection:text-primary-foreground
                defaultTextSelectionColors = TextSelectionColors(
                    backgroundColor = palette.getValue(ColorTokens.primary),
                    handleColor = palette.getValue(ColorTokens.primaryForeground),
                )
                properties[ColorProps] = palette
                properties[DimProps] = if (isDark) themeDarkSemanticDimensions else themeLightSemanticDimensions
            }

            @Composable
            fun ShadcnTheme(
                mode: Mode = if (isSystemInDarkTheme()) Mode.Dark else Mode.Light,
                onModeChanged: @Composable (mode: Mode) -> Unit = {},
                content: @Composable () -> Unit,
            ) {
                val isDark = mode == Mode.Dark
                val isDarkState = remember { mutableStateOf(isDark) }
                LaunchedEffect(isDark) {
                    isDarkState.value = isDark
                }
                CompositionLocalProvider(LocalThemeIsDark provides isDarkState) {
                    val currentIsDark by isDarkState
                    onModeChanged(if (currentIsDark) Mode.Dark else Mode.Light)
                    ShadcnTheme(content)
                }
            }
            """.trimIndent() + "\n",
        )
    }

    private fun tokenTypeToClassName(token: CollectedToken): TypeName = when {
        token.type == "color" -> colorClass
        token.type == "dimension" -> dpClass
        token.type == "custom-fontStyle" -> textStyleClass
        token.type == "custom-shadow" -> ClassName(packageName, "TokenShadow")
        token.type == "string" -> String::class.asTypeName()
        token.type == "number" -> Float::class.asTypeName()
        else -> String::class.asTypeName()
    }

    private fun primitiveInitializer(token: CollectedToken, codegen: ValueCodegen): String {
        return when (token.type) {
            "color", "dimension", "string", "number" ->
                codegen.resolveValue(token.valueString, token.isReference)

            "custom-fontStyle" -> {
                val json = token.rawValue.jsonObject
                codegen.textStyleFromJson(json)
            }

            "custom-shadow" -> {
                val json = token.rawValue.jsonObject
                codegen.shadowFromJson(json)
            }

            else -> codegen.literalValue(token.valueString)
        }
    }
}
